spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframwork.web : debug
    sql : debug
    jdbc : off
    jdbc.sqlonly : debug
